---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Installing packages
    package: 
        name: "{{ item }}"
        state: present
    loop:
        - vim
        - zsh
        - wget
        - curl
        - tmux
        - kubernetes-cli
        - docker
        - terraform
        - terragrunt
        - tree
        - gpg
        - jq
        - yq
        - pyenv

  - name: Creating github dir
    file:
        path: ~/github
        state: directory

  - name: Checking for dot config git
    stat:
        path: ~/github/config
    register: config_dir

  - name: Getting dot config repo
    git:
        repo: "https://github.com/madsonic/config"
        dest: ~/github/config
        clone: no
        force: yes

  - name: Softlinking to dot config
    file:
        path: "~/{{ item }}"
        src: "~/github/config/{{ item }}"
        state: link
        force: yes
    loop:
        - ".vimrc"
        - ".zshrc"
        - ".gitconfig"
        - ".git-completion.bash"
        - ".tmux.conf"

  - name: "Change login shell to zsh"
    user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
    become: yes

  - name: "Checking oh my zsh existence"
    stat:
      path: ~/.oh-my-zsh
    register: zsh_installed

  - name: "Downloading oh my zsh"
    get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh 
        dest: /tmp/install-zsh.sh
        mode: u+rwx
    when: zsh_installed.stat.exists == false
  
  - name: "Installing oh my zsh"
    command: sh -c /tmp/install-zsh.sh
    when: zsh_installed.stat.exists == false

  - name: Creating tmux plugin dir
    file:
        path: ~/.tmux/plugins
        state: directory

  - name: Installing tmux plugin manager
    git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: ~/.tmux/plugins/tpm

  - name: Installing apps
    command: "brew cask install {{ item }}"
    loop:
        - karabiner-elements
        - alfred
        - spotify
        - google-chrome
        - iterm2
        - spectacle
        - gpg-suite
        - slack
        - telegram
        - whatsapp
        - postman
